name: $(GITVERSION_FullSemVer)
trigger:
  - master
  
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'any cpu'
  buildConfiguration: 'Release'
stages:
  - stage: Build
    displayName: Build
    jobs:
    - template: templates/commonbuildtasks.yml
     
  - stage: PublishToXRMToolBoxStoreFeed
    displayName: Publish to XRMToolBox Store
    jobs:
      - job: PublishToXRMToolBoxStoreJob
        displayName: Publish to XRMToolBox Store Feed
        steps:
          - checkout: none
          - download: current
            displayName: Download NuGet package artifact
            artifact: Capgemini.Xrm.DataMigration.XrmToolBoxPlugin
            
          #- task: NuGetCommand@2
          #  displayName: 'NuGet push'
          #  inputs:
          #    command: push
          #     packagesToPush: '$(Pipeline.Workspace)/Capgemini.Xrm.DataMigration.Engine/*.nupkg'
          #     publishVstsFeed: 'e64f1ace-b73a-42b0-8b8e-4b2fdbdac2c9'
          #    nuGetFeedType: external
          #    publishFeedCredentials: CapgeminiUkKey

          - task: NuGetCommand@2
            displayName: 'Push to private feed'
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/Capgemini.Xrm.DataMigration.Engine/*.nupkg'
              publishVstsFeed: 'e64f1ace-b73a-42b0-8b8e-4b2fdbdac2c9'


