jobs: 
  - job: CommonBuildJob
    variables:
      - name: solution
        value: '**/*.sln'
      - name: buildPlatform
        value: 'Any CPU'
      - name: buildConfiguration
        value: 'Release'
    displayName: Build test and analyse
    steps:
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 4.4.1'
        inputs:
          versionSpec: 4.4.1

      - task: gittools.gitversion.gitversion-task.GitVersion@5
        displayName: GitVersion
        inputs:
          runtime: full
          configFilePath: '$(Build.SourcesDirectory)\GitVersion.yml'
          updateAssemblyInfo: true

      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          restoreSolution: '$(solution)'
          vstsFeed: '25162f08-da5e-4c04-bac0-40216eaa4bf9'
          restoreDirectory: ../packages

      - task: SonarCloudPrepare@1
        displayName: Prepare SonarCloud
        inputs:
          SonarCloud: 'Capgemini Accelerator Token'
          organization: 'capgemini-1'
          scannerMode: 'MSBuild'
          projectKey: 'xrm-datamigration-xrmtoolbox'
          projectName: 'xrm-datamigration-xrmtoolbox'
          projectVersion: '$(GitVersion.NuGetVersionV2)'

      - task: VSBuild@1
        displayName: 'Build solution **\*.sln'
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: VSTest@2
        displayName: Run tests
        inputs:
          searchFolder: Capgemini.Xrm.XrmToolBoxPlugins
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          codeCoverageEnabled: true
          testAssemblyVer2: |
            **\*Tests*.dll
            !**\*Integration*.dll
            !**\obj\**

      - task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@20
        displayName: 'WhiteSource Bolt'
        inputs:
          cwd: '$(Build.SourcesDirectory)'

      - task: SonarCloudAnalyze@1
        displayName: 'Run Code Analysis'
      - task: SonarCloudPublish@1
        displayName: Publish SonarCloud results
        inputs:
          pollingTimeoutSec: '300'

      - task: PublishSymbols@2
        displayName: 'Publish symbols path'
        inputs:
          SearchPattern: '**\bin\**\*.pdb'
          PublishSymbols: false
        continueOnError: true

      - task: NuGetCommand@2
        displayName: 'NuGet pack'
        inputs:
          command: pack
          packagesToPack: Capgemini.Xrm.XrmToolBoxPlugins/Capgemini.Xrm.DataMigration.XrmToolBox/Capgemini.Xrm.DataMigration.XrmToolBoxPlugin.nuspec            
          packDestination: '$(Build.ArtifactStagingDirectory)/package'
          versioningScheme: byEnvVar
          versionEnvVar: GitVersion.NuGetVersionV2

      - task: CopyFiles@2
        displayName: Copy tests to staging directory
        inputs:
          Contents: '**/$(buildConfiguration)/**'
          SourceFolder: Capgemini.Xrm.XrmToolBoxPlugins
          TargetFolder: '$(Build.ArtifactStagingDirectory)/tests'

      - publish: $(Build.ArtifactStagingDirectory)/package
        displayName: Publish NuGet artifact
        artifact: Capgemini.Xrm.DataMigration.XrmToolBoxPlugin

      - publish: $(Build.ArtifactStagingDirectory)/tests
        displayName: Publish tests
        artifact: Capgemini.Xrm.DataMigration.XrmToolBoxPlugin.Tests
